backend:
  name: test-repo
  branch: main

# Media folder settings
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artwork"
    label: "Artwork"
    folder: "content/artwork"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Price",
          name: "price",
          widget: "number",
          value_type: "float",
          min: 0,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
          min: 1,
        }
      - { label: "Width", name: "width", widget: "number" }
      - { label: "Height", name: "height", widget: "number" }
      - {
          label: "Unit",
          name: "unit",
          widget: "select",
          options: ["inches", "cm"],
          default: "inches",
        }
      - { label: "Medium", name: "medium", widget: "string" }
      - { label: "Creation Date", name: "createdAt", widget: "datetime" }
      - {
          label: "Available",
          name: "available",
          widget: "boolean",
          default: true,
        }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "description", widget: "text" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }
