backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artwork"
    label: "Artwork"
    folder: "content/artwork"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0}
      - {label: "Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Width", name: "width", widget: "number"}
      - {label: "Height", name: "height", widget: "number"}
      - {label: "Unit", name: "unit", widget: "select", options: ["inches", "cm"]}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Creation Date", name: "createdAt", widget: "datetime"}
      - {label: "Available", name: "available", widget: "boolean", default: true}